# Generated by Django 5.0.4 on 2024-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_listing_email_listing_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
