# Generated by Django 5.0.4 on 2024-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='phone',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
